include: package:flutter_lints/flutter.yaml

linter:
  rules:
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    void_checks: true
    package_names: true
    sort_pub_dependencies: true
    directives_ordering: true
    no_leading_underscores_for_local_identifiers: true
    use_build_context_synchronously: true
    require_trailing_commas: true
    depend_on_referenced_packages: true
