name: free_dictionary_app
description: "Flutter dictionary App powered by the Free Dictionary API"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: 2.5.0
  flutter_mobx: 2.3.0
  google_fonts: 6.2.1
  dio: 5.8.0+1
  pretty_dio_logger: 1.4.0
  get_it: 8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 6.0.0
  mobx_codegen: 2.7.1
  build_runner: 2.4.15

flutter:

  uses-material-design: true

  assets:
    - assets/
