name: free_dictionary
description: A free dictionary app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: any
  cupertino_icons: ^1.0.8
  dio: 5.8.0+1
  dio_cache_interceptor: 4.0.3
  equatable: 2.0.7
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_mobx: 2.3.0
  font_awesome_flutter: 10.8.0
  gap: 3.0.1
  get_it: 8.0.3
  go_router: 15.2.0
  google_fonts: 6.2.1
  intl: any
  just_audio: 0.10.4
  mobx: 2.5.0
  pretty_dio_logger: 1.4.0
  shared_preferences: 2.5.3
dev_dependencies:
  build_runner: 2.4.15
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.7.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
